services:
  api:
    container_name: dwapi
    build:
        dockerfile: Dockerfile
        context: .
    ports:
        - 4652:8080
    depends_on: ["postgres"]
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    networks:
        local-network:

  postgres:
    image: postgres
    container_name: dw-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
        local-network:
            aliases:
                - "sql" 
    volumes:
    - postgres_data:/var/lib/docker/volumes/a407acd131c474a6e877480094f4afd0c1486a52979ac44f41302f5523d15cf4/_data 

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    command: postgres sslmode=disable
    networks:
        local-network:
networks:
  local-network:
    driver: bridge
volumes:
  pgadmin_data:
  postgres_data:
    external: true
  